version: "3.2"
services:
  builder:
    image: "node:latest"
    container_name: "event-collector"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      KAFKA_DEFAULT_TOPIC: test
      KAFKA_CLIENT_ID: dev-event-collector
      KAFKA_MAX_MSG_SIZE: 1000000
      KAFKA_DEBUG: "True"
    ports:
      - "${EXTERNAL_PORT}:3000"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CREATE_TOPICS: "test:2:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock