version: 2.1

orbs:
   azure-acr: circleci/azure-acr@x.y.z

executors:
 dlc:
  azure-acr/default:
    dlc: true
  

workflows:
  build-and-publish-docker-image:
    jobs:
      - azure-acr/build-and-push-image:
        executor: dlc
        login-server-name: exampleregistry.azurecr.io
        registry-name: exampleregistry
        repo: example-repository
        tag: $CIRCLE_TAG