version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    # pre-built images: https://circleci.com/docs/2.0/circleci-images/
    docker:
      - image: circleci/node:10-browsers
      - image: circleci/mongo:3.6
        environment:
          - MONGODB_USERNAME: mongouser
          - MONGODB_PASSWORD: mongopass
    steps:
      - setup_remote_docker
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Install mongo client
          command: |
            sudo apt-get install -y mongodb
      - checkout
      - run:
          name: Connect to DB
          command: mongo --username mongouser --password mongopass --eval "printjson(db.apikeys.count());" dbname